
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://deepshikaarasu.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: "/deepshikaarasu.github.io"

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Deepshika Arasu"
title: "Deepshika Arasu"
description: "This is my personal website where you can find out more about me and my interests in neuroscience, feminism, policy, watercolours among other things ."
keywords: "deepshika, arasu, "
#favicon: "/img/favicon.ico"

################
# Header layout #
################

#black-favicon: ""
#logo: "" # leave blank if you don't want a logo

background-img: "/img/introbg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Hi! Welcome to my website"


me-img: "/img/profilepic.jpeg"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

# me-img: "https://graph.facebook.com/user_id/picture?type=large&width=500&height=500"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

# me-img: "https://github.com/user_name.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: False

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "personal-jekyll-theme"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/nitw.png"
    date: "August 2014 - August 2018"
    description: "B Tech. in Biotechnology"    
  - image: "/img/timeline/Charite-1.jpg"
    date: "October 2018 - August 2019"
    description: "Neurasmus - M.Sc. in Neuroscience"
  - image: "/img/timeline/VU.jpg"
    date: "October 2018 - August 2019"
    description: "Neurasmus - M.Sc. in Neuroscience"  
  - image: "/img/timeline/VU.jpg"
    date: "Someday soon"
    description: "PhD"  
    

# First image of the Timeline

#timeline-img: ""

###########
# Contact #
###########

email: "deepshikaarasu@gmail.com"


# Set a url pointing to your publish PGP Public Key here, and it will appear in the Contact section
pgp: False

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Deepshika Arasu is currently pursuing her PhD at Poietis under the Marie Curie Fellowship program ASCTN."
author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/deepshika.arasu"
  - title: "twitter"
    url: "https://twitter.com/deepzillu"
  - title: "github"
    url: "https://github.com/deepshika96"
  #- title: "bitcoin"
  #  url: "https://blockchain.info/address/1LHuKC9Em3KA5yoZaf7nngnNdf9K7s2gSi"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

err-404-img: "/img/HTML-404-Error-Page.gif"

##################
# GPG on Keybase #
##################

keybase-username: 
keybase-in-social: False
keybase-in-footer: False 

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Timeline: 'timeline'
  Projects: 'projects'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
