url: 'https://deepshika96.github.io'
baseurl: /website
google-tracking-id: ''
force-https: true
lang: en
author: Deepshika Arasu
title: Deepshika Arasu
description: ''
keywords: 'deepshika, arasu, '
black-favicon: "/website/img/introbgcopy.jpg"
background-img: /website/img/introbgcopy.jpg
dynamic-typing: True
shuffle: True
loop: True
loop-count: False
type-speed: 10
start-delay: 200
delete-delay: 5000
lines:
  - text: "Hi! Welcome to my website"
me-img: /img/Deepshika.jpeg
color-browser: '#000000'
apple-status-bar-style: black
web-app-mode: true
icon-36p: /img/web-app/icon-36p.png
icon-48p: /img/web-app/icon-48p.png
icon-72p: /img/web-app/icon-72p.png
icon-96p: /img/web-app/icon-96p.png
icon-144p: /img/web-app/icon-144p.png
icon-192p: /img/web-app/icon-192p.png
enable-gesture-navigation: true
post-preview-words: 96
paginate: 5
email-share: true
fb-share: true
twitter-share: true
linkedin-share: true
reddit-share: true
google-plus-share: true
tumblr-share: true
pinterest-share: true
pocket-share: true
vkontakte-share: true
disqus-shortname: personal-jekyll-theme
syntax-highlight: true
events:
  - image: /img/timeline/ub.png
    date: May 2021 - current
    description: PhD in Biomedcine
  - image: /img/timeline/VU.jpg
    date: October 2018 - August 2019
    description: Neurasmus - M.Sc. in Neuroscience
  - image: /img/timeline/Charite-1.jpg
    date: October 2018 - August 2019
    description: Neurasmus - M.Sc. in Neuroscience
  - image: /img/timeline/nitw.png
    date: August 2014 - August 2018
    description: B Tech. in Biotechnology  
timeline-img: "/img/timeline/download1.png"
email: deepshika96@gmail.com
pgp: false
author_blurb: >-
  Deepshika Arasu is currently pursuing her PhD at Poietis under the Marie Curie
  Fellowship program ASCTN.
author_blurb_image: /img/Deepshika.jpeg
social:
  - title: facebook
    url: 'https://facebook.com/deepshika.arasu'
  - title: twitter
    url: 'https://twitter.com/deepzillu'
  - title: github
    url: 'https://github.com/deepshika96'
  - title: rss
    url: /feed.xml
err-404-img: /img/HTML-404-Error-Page.gif
keybase-username: null
keybase-in-social: false
keybase-in-footer: false
pages_list:
  About: about
  Timeline: timeline
  Projects: projects
  Contact: contact
exclude:
  - LICENSE
  - README.md
  - CONTRIBUTING
  - CONTRIBUTORS
  - scripts
paginate_path: 'blog/page:num/'
sass:
  style: compressed
gems:
  - jekyll-paginate
  - jemoji
